### ISSUE TITLE
Case4: 如果两个 cell 的高度总和小于 imageView的高度，cell 高度就不对了

### ISSUE THREAD

**Issue by CoderPeteRuan** [zekunyan/AutolayoutExampleWithMasonry#3]
在 Case4:UITableView 变高中 发现一个问题 :
![snip20170630_1](https://user-images.githubusercontent.com/26851274/27719180-320f0158-5d83-11e7-8d8f-34e4d01eeda0.png)

如上图，如果我把 `titleLabel` 和 `contentLabel` 的字体变小，然后在 `contentLabel` 一行的情况下，cell 的高度就不对了，因为这时候 `imageView` 的高度大于两个 `Label` 高度的总和，所以 cell 的高度应当等于 `imageView` 的最大 y 值加上 someMargin，这时候要怎么解决？或者说这种情况下约束怎么加（要求不手动算高）？

**Comment by zekunyan** [comment]
给imageView跟Cell底部加约束就好了啊。。。
