### ISSUE TITLE
Case1

### ISSUE THREAD

**Issue by Winter-J-27** [zekunyan/AutolayoutExampleWithMasonry#4]
我把_label2的content compression改成1000 [_label2 setContentCompressionResistancePriority:UILayoutPriorityRequired forAxis:UILayoutConstraintAxisHorizontal]; 或者把设置content hugging和content compression的这四行代码都注释了..运行起来效果好像没区别呀

**Comment by Damon-YJ** [comment]
我把_label2的content compression改成1000   `[_label2 setContentCompressionResistancePriority:UILayoutPriorityRequired
                                             forAxis:UILayoutConstraintAxisHorizontal];` 或者把设置`content hugging`和`content compression`的这四行代码都注释了..运行起来效果好像没区别呀

**Comment by zekunyan** [comment]
系统会有默认行为
